version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: newspaper-db
    environment:
      POSTGRES_DB: newspaper_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local